### ISSUE TITLE
Script 3 - Create EDA

### ISSUE THREAD

**Issue by DanielCairns** [UBC-MDS/eurovision_contest_rank_analysis#12]
A third script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that dataset. This should take two arguments:

    a path/filename pointing to the data

    a path/filename prefix where to write the figure to and what to call it (e.g., results/this_eda.png)

**Comment by mrnabiz** [comment]
Usage:
python eurovision_eda.py --input_file="../data/raw/eurovision.csv" --output_dir="eda_data/figures"
